"""Type stubs for plotnine library.

This module provides type stubs for plotnine to improve type checking.
Plotnine is a statistical plotting library based on ggplot2.
"""

from typing import Any

def aes(*args: Any, **kwargs: Any) -> Any: ...
def facet_wrap(*args: Any, **kwargs: Any) -> Any: ...
def geom_bar(*args: Any, **kwargs: Any) -> Any: ...
def geom_jitter(*args: Any, **kwargs: Any) -> Any: ...
def labs(*args: Any, **kwargs: Any) -> Any: ...

class ggplot:
    def __init__(self, data: Any, *args: Any, **kwargs: Any) -> None: ...
    def __add__(self, other: Any) -> Any: ...

