"""Type stubs for sklearn.tree module."""

from typing import Any

class DecisionTreeRegressor:
    """Type stub for sklearn.tree.DecisionTreeRegressor."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def fit(self, X: Any, y: Any, *args: Any, **kwargs: Any) -> Any: ...
    def predict(self, X: Any, *args: Any, **kwargs: Any) -> Any: ...
    def decision_path(self, X: Any, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

def plot_tree(*args: Any, **kwargs: Any) -> Any: ...

